ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_method VARCHAR(10) NOT NULL DEFAULT 'NONE';
ALTER TABLE users ADD COLUMN mfa_secret VARCHAR(255);
