CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    amount DECIMAL(19, 4) NOT NULL,
    category VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submission_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decision_date TIMESTAMP,
    processed_date TIMESTAMP,
    owner_id BIGINT NOT NULL,
    department_id BIGINT,
    tenant_id BIGINT NOT NULL,
    approved_by BIGINT,
    rejected_by BIGINT,
    processed_by BIGINT,
    updated_at TIMESTAMP,
    CONSTRAINT fk_expense_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_expense_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_expense_rejected_by FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_expense_processed_by FOREIGN KEY (processed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_expense_tenant ON expenses(tenant_id);
CREATE INDEX IF NOT EXISTS idx_expense_department ON expenses(department_id);
CREATE INDEX IF NOT EXISTS idx_expense_owner ON expenses(owner_id);
CREATE INDEX IF NOT EXISTS idx_expense_status ON expenses(status);
